// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCMVAKBFUAiGrg8hMi_JnvlVN1IGkjz_jI",
    authDomain: "flutterweb-c3f6b.firebaseapp.com",
    projectId: "flutterweb-c3f6b",
    storageBucket: "flutterweb-c3f6b.appspot.com",
    messagingSenderId: "1924249476",
    appId: "1:1924249476:web:4a88746afe8c28d508cfd1",
    measurementId: "G-96BVBXHMCE"
   // apiKey: 'AIzaSyCbr-GSYMM0fof0qa_D1QDwGYKg95tX_jE',
   // appId: '1:923212413067:web:1de47f0b5ea28c5febbc8e',
   // messagingSenderId: '923212413067',
   // projectId: 'flutterweb-ed38e',
   // authDomain: 'flutterweb-ed38e.firebaseapp.com',
   // storageBucket: 'flutterweb-ed38e.appspot.com',
   // measurementId: 'G-JJ0BXGLYGF',
  );
}
